INSERT INTO words_library (language, word_civilian, word_undercover) VALUES
('ID', 'Kopi', 'Teh'),
('ID', 'Nasi Goreng', 'Mie Goreng'),
('ID', 'Burger', 'Pizza'),
('ID', 'Es Krim', 'Gelato'),
('ID', 'Susu', 'Yogurt'),
('ID', 'Apel', 'Jeruk'),
('ID', 'Roti', 'Kue'),
('ID', 'Soto', 'Bakso'),
('ID', 'Air Mineral', 'Jus'),
('ID', 'Cokelat', 'Permen'),
('ID', 'Kucing', 'Anjing'),
('ID', 'Harimau', 'Singa'),
('ID', 'Burung Hantu', 'Elang'),
('ID', 'Ikan', 'Gurita'),
('ID', 'Kelinci', 'Hamster'),
('ID', 'Kuda', 'Keledai'),
('ID', 'Ayam', 'Bebek'),
('ID', 'Sapi', 'Kambing'),
('ID', 'Kupu-kupu', 'Lebah'),
('ID', 'Ular', 'Kadal'),
('ID', 'Sekolah', 'Kampus'),
('ID', 'Rumah', 'Apartemen'),
('ID', 'Bandara', 'Stasiun'),
('ID', 'Perpustakaan', 'Toko Buku'),
('ID', 'Pantai', 'Gunung'),
('ID', 'Pasar', 'Supermarket'),
('ID', 'Bioskop', 'Teater'),
('ID', 'Kantor', 'Bank'),
('ID', 'Restoran', 'Kafe'),
('ID', 'Hotel', 'Vila'),
('ID', 'Dokter', 'Perawat'),
('ID', 'Polisi', 'Tentara'),
('ID', 'Guru', 'Dosen'),
('ID', 'Koki', 'Pelayan'),
('ID', 'Pilot', 'Masinis'),
('ID', 'Penulis', 'Wartawan'),
('ID', 'Artis', 'Model'),
('ID', 'Petani', 'Nelayan'),
('ID', 'Arsitek', 'Insinyur'),
('ID', 'Pengacara', 'Hakim'),
('ID', 'Ponsel', 'Tablet'),
('ID', 'Laptop', 'Komputer'),
('ID', 'Buku', 'Majalah'),
('ID', 'Pulpen', 'Pensil'),
('ID', 'Kipas Angin', 'AC'),
('ID', 'Mobil', 'Motor'),
('ID', 'Sepeda', 'Skuter'),
('ID', 'Jam Tangan', 'Jam Dinding'),
('ID', 'Lampu', 'Lilin'),
('ID', 'Gitar', 'Piano'),
('ID', 'Payung', 'Jas Hujan'),
('ID', 'Kacamata', 'Lensa Kontak'),
('ID', 'Tas', 'Dompet'),
('ID', 'Sepatu', 'Sandal'),
('ID', 'Topi', 'Helm'),
('ID', 'Kemeja', 'Kaos'),
('ID', 'Celana', 'Rok'),
('ID', 'Jas', 'Jaket'),
('ID', 'Dasi', 'Syall'),
('ID', 'Sarung Tangan', 'Kaos Kaki'),
('ID', 'Sabun', 'Sampo'),
('ID', 'Sikat Gigi', 'Pasta Gigi'),
('ID', 'Handuk', 'Keset'),
('ID', 'Cermin', 'Sisir'),
('ID', 'Bantal', 'Guling'),
('ID', 'Selimut', 'Sprei'),
('ID', 'Kasur', 'Tikar'),
('ID', 'Pintu', 'Jendela'),
('ID', 'Atap', 'Lantai'),
('ID', 'Dapur', 'Kamar Mandi'),
('ID', 'Piring', 'Mangkok'),
('ID', 'Sendok', 'Garpu'),
('ID', 'Gelas', 'Cangkir'),
('ID', 'Wajan', 'Panci'),
('ID', 'Pisau', 'Gunting'),
('ID', 'Kulkas', 'Mesin Cuci'),
('ID', 'Televisi', 'Radio'),
('ID', 'Kamera', 'Teleskop'),
('ID', 'Baterai', 'Charger'),
('ID', 'Remote', 'Joystick'),
('ID', 'Emas', 'Perak'),
('ID', 'Besi', 'Baja'),
('ID', 'Kayu', 'Bambu'),
('ID', 'Batu', 'Pasir'),
('ID', 'Tanah', 'Lumpur'),
('ID', 'Air', 'Api'),
('ID', 'Angin', 'Awan'),
('ID', 'Matahari', 'Bulan'),
('ID', 'Bintang', 'Planet'),
('ID', 'Hujan', 'Salju'),
('ID', 'Pagi', 'Sore'),
('ID', 'Siang', 'Malam'),
('ID', 'Musim Panas', 'Musim Dingin'),
('ID', 'Timur', 'Barat'),
('ID', 'Utara', 'Selatan'),
('ID', 'Kiri', 'Kanan'),
('ID', 'Atas', 'Bawah'),
('ID', 'Depan', 'Belakang'),
('ID', 'Cepat', 'Lambat'),
('ID', 'Keras', 'Lunak'),
('ID', 'Panas', 'Dingin'),
('ID', 'Manis', 'Asin'),
('ID', 'Pahit', 'Asam'),
('ID', 'Wangi', 'Busuk'),
('ID', 'Terang', 'Gelap'),
('ID', 'Bersih', 'Kotor'),
('ID', 'Baru', 'Lama'),
('ID', 'Mahal', 'Murah'),
('ID', 'Kaya', 'Miskin'),
('ID', 'Pintar', 'Bodoh'),
('ID', 'Berani', 'Takut'),
('ID', 'Senang', 'Sedih'),
('ID', 'Marah', 'Tenang'),
('ID', 'Capek', 'Segar'),
('ID', 'Sakit', 'Sehat'),
('ID', 'Hidup', 'Mati'),
('ID', 'Lari', 'Jalan'),
('ID', 'Lompat', 'Terbang'),
('ID', 'Berenang', 'Menyelam'),
('ID', 'Makan', 'Minum'),
('ID', 'Tidur', 'Bangun'),
('ID', 'Baca', 'Tulis'),
('ID', 'Dengar', 'Bicara'),
('ID', 'Lihat', 'Raba'),
('ID', 'Beli', 'Jual'),
('ID', 'Pinjam', 'Kasih'),
('ID', 'Datang', 'Pergi'),
('ID', 'Naik', 'Turun'),
('ID', 'Buka', 'Tutup'),
('ID', 'Tarik', 'Dorong'),
('ID', 'Angkat', 'Lempar'),
('ID', 'Tangkap', 'Lepas'),
('ID', 'Potong', 'Sambung'),
('ID', 'Lipat', 'Gulung'),
('ID', 'Cuci', 'Jemur'),
('ID', 'Masak', 'Makan'),
('ID', 'Sepak Bola', 'Futsal'),
('ID', 'Bola Basket', 'Bola Voli'),
('ID', 'Tenis', 'Badminton'),
('ID', 'Golf', 'Biliar'),
('ID', 'Catur', 'Kartu'),
('ID', 'Ludo', 'Monopoli'),
('ID', 'Gitar Listrik', 'Bass'),
('ID', 'Drum', 'Simbal'),
('ID', 'Biola', 'Cello'),
('ID', 'Seruling', 'Saksofon'),
('ID', 'Terompet', 'Harmonika'),
('ID', 'Lukisan', 'Patung'),
('ID', 'Puisi', 'Novel'),
('ID', 'Film', 'Drama'),
('ID', 'Konser', 'Pesta'),
('ID', 'Museum', 'Galeri'),
('ID', 'Taman', 'Hutan'),
('ID', 'Sungai', 'Danau'),
('ID', 'Laut', 'Samudra'),
('ID', 'Pulau', 'Benua'),
('ID', 'Gurun', 'Sabana'),
('ID', 'Gua', 'Lembah'),
('ID', 'Pelangi', 'Kilat'),
('ID', 'Gempa', 'Banjir'),
('ID', 'Robot', 'Alien'),
('ID', 'Sihir', 'Sains'),
('ID', 'Pahlawan', 'Penjahat'),
('ID', 'Raja', 'Ratu'),
('ID', 'Pangeran', 'Putri'),
('ID', 'Naga', 'Dinosaurus'),
('ID', 'Hantu', 'Zombi'),
('ID', 'Vampir', 'Manusia Serigala'),
('ID', 'Oksigen', 'Karbon Dioksida'),
('ID', 'Atom', 'Molekul'),
('ID', 'Sel', 'Jaringan'),
('ID', 'Otak', 'Jantung'),
('ID', 'Paru-paru', 'Hati'),
('ID', 'Lambung', 'Usus'),
('ID', 'Tulang', 'Otot'),
('ID', 'Darah', 'Saraf'),
('ID', 'Akar', 'Batang'),
('ID', 'Daun', 'Bunga'),
('ID', 'Buah', 'Biji'),
('ID', 'Hutan Bakau', 'Hutan Hujan'),
('ID', 'Kopi Hitam', 'Latte'),
('ID', 'Teh Hijau', 'Teh Tarik'),
('ID', 'Nasi Putih', 'Nasi Kuning'),
('ID', 'Rendang', 'Opor'),
('ID', 'Gudeg', 'Rawon'),
('ID', 'Pempek', 'Otak-otak'),
('ID', 'Sate Ayam', 'Sate Kambing'),
('ID', 'Martabak Manis', 'Martabak Telur'),
('ID', 'Klepon', 'Onde-onde'),
('ID', 'Cendol', 'Dawet'),
('ID', 'Kerupuk', 'Emping'),
('ID', 'Sambal Terasi', 'Sambal Matah');